### ISSUE TITLE
Keyboard shortcuts for specific brushes

### ISSUE THREAD

**Issue by luisherranz** [aKzenT/gptbrushes#5]
I'm loving this! Thank you a lot.

Is there any chance to add support for keyboard shortcuts? I'd love to be able to apply some of my common brushes without using the mouse.

**Comment by aKzenT** [comment]
Hey,

that is a good idea. Unfortunately I don't have a lot of time right now to implement new features. Are you interested in providing this as a pull request?

**Comment by luisherranz** [comment]
I can take a look at it, yes.

**Comment by luisherranz** [comment]
The truth is that after a while using this, I don't miss having shortcuts 🙂

So I think we can close this.
